FROM mdillon/postgis:9.6
MAINTAINER Benito Zaragozí <benizar@gmail.com>

# base
RUN apt-get update
RUN apt-get install -y build-essential checkinstall apt-utils
RUN apt-get install -y wget git-core
RUN apt-get install -y postgresql-server-dev-9.6


# copy and compile dw
COPY /dw/ /dw/

RUN cd dw &&\
	make &&\
	make install &&\
	cd .. &&\
	rm -Rf dw


# Clone and compile pg_popyramids (a dw extension)
COPY /popyramids/ /popyramids/

RUN cd popyramids &&\
	make &&\
	make install &&\
	cd .. &&\
	rm -Rf popyramids


# copy and compile geohash-extra
COPY /geohash-extra/ /geohash-extra/

RUN cd geohash-extra &&\
	make &&\
	make install &&\
	cd .. &&\
	rm -Rf geohash-extra

# clean packages
#RUN apt-get remove -y build-essential checkinstall apt-utils wget git-core postgresql-server-dev-9.6

RUN mkdir -p /docker-entrypoint-initdb.d
COPY ./init-dw.sh /docker-entrypoint-initdb.d/init-dw.sh



# add backup scripts
ADD /dbutils/backup.sh /usr/local/bin/backup
ADD /dbutils/restore.sh /usr/local/bin/restore
ADD /dbutils/list-backups.sh /usr/local/bin/list-backups
ADD /dbutils/shell.sh /usr/local/bin/shell

# make them executable
RUN chmod +x /usr/local/bin/restore
RUN chmod +x /usr/local/bin/list-backups
RUN chmod +x /usr/local/bin/backup
RUN chmod +x /usr/local/bin/shell
