CREATE TABLE stage.censo_ccaa_2001_melt AS (
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy0 as xy, xx0 as xx, rxy_0_1 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy1 as xy, xx1 as xx, rxy_1_2 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy2 as xy, xx2 as xx, rxy_2_3 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy3 as xy, xx3 as xx, rxy_3_4 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy4 as xy, xx4 as xx, rxy_4_5 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy5 as xy, xx5 as xx, rxy_5_6 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy6 as xy, xx6 as xx, rxy_6_7 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy7 as xy, xx7 as xx, rxy_7_8 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy8 as xy, xx8 as xx, rxy_8_9 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy9 as xy, xx9 as xx, rxy_9_10 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy10 as xy, xx10 as xx, rxy_10_11 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy11 as xy, xx11 as xx, rxy_11_12 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy12 as xy, xx12 as xx, rxy_12_13 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy13 as xy, xx13 as xx, rxy_13_14 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy14 as xy, xx14 as xx, rxy_14_15 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy15 as xy, xx15 as xx, rxy_15_16 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy16 as xy, xx16 as xx, rxy_16_17 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy17 as xy, xx17 as xx, rxy_17_18 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy18 as xy, xx18 as xx, rxy_18_19 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy19 as xy, xx19 as xx, rxy_19_20 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy20 as xy, xx20 as xx, rxy_20_21 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy21 as xy, xx21 as xx, rxy_21_22 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy22 as xy, xx22 as xx, rxy_22_23 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy23 as xy, xx23 as xx, rxy_23_24 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy24 as xy, xx24 as xx, rxy_24_25 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy25 as xy, xx25 as xx, rxy_25_26 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy26 as xy, xx26 as xx, rxy_26_27 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy27 as xy, xx27 as xx, rxy_27_28 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy28 as xy, xx28 as xx, rxy_28_29 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy29 as xy, xx29 as xx, rxy_29_30 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy30 as xy, xx30 as xx, rxy_30_31 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy31 as xy, xx31 as xx, rxy_31_32 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy32 as xy, xx32 as xx, rxy_32_33 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy33 as xy, xx33 as xx, rxy_33_34 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy34 as xy, xx34 as xx, rxy_34_35 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy35 as xy, xx35 as xx, rxy_35_36 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy36 as xy, xx36 as xx, rxy_36_37 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy37 as xy, xx37 as xx, rxy_37_38 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy38 as xy, xx38 as xx, rxy_38_39 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy39 as xy, xx39 as xx, rxy_39_40 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy40 as xy, xx40 as xx, rxy_40_41 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy41 as xy, xx41 as xx, rxy_41_42 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy42 as xy, xx42 as xx, rxy_42_43 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy43 as xy, xx43 as xx, rxy_43_44 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy44 as xy, xx44 as xx, rxy_44_45 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy45 as xy, xx45 as xx, rxy_45_46 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy46 as xy, xx46 as xx, rxy_46_47 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy47 as xy, xx47 as xx, rxy_47_48 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy48 as xy, xx48 as xx, rxy_48_49 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy49 as xy, xx49 as xx, rxy_49_50 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy50 as xy, xx50 as xx, rxy_50_51 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy51 as xy, xx51 as xx, rxy_51_52 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy52 as xy, xx52 as xx, rxy_52_53 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy53 as xy, xx53 as xx, rxy_53_54 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy54 as xy, xx54 as xx, rxy_54_55 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy55 as xy, xx55 as xx, rxy_55_56 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy56 as xy, xx56 as xx, rxy_56_57 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy57 as xy, xx57 as xx, rxy_57_58 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy58 as xy, xx58 as xx, rxy_58_59 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy59 as xy, xx59 as xx, rxy_59_60 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy60 as xy, xx60 as xx, rxy_60_61 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy61 as xy, xx61 as xx, rxy_61_62 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy62 as xy, xx62 as xx, rxy_62_63 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy63 as xy, xx63 as xx, rxy_63_64 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy64 as xy, xx64 as xx, rxy_64_65 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy65 as xy, xx65 as xx, rxy_65_66 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy66 as xy, xx66 as xx, rxy_66_67 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy67 as xy, xx67 as xx, rxy_67_68 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy68 as xy, xx68 as xx, rxy_68_69 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy69 as xy, xx69 as xx, rxy_69_70 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy70 as xy, xx70 as xx, rxy_70_71 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy71 as xy, xx71 as xx, rxy_71_72 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy72 as xy, xx72 as xx, rxy_72_73 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy73 as xy, xx73 as xx, rxy_73_74 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy74 as xy, xx74 as xx, rxy_74_75 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy75 as xy, xx75 as xx, rxy_75_76 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy76 as xy, xx76 as xx, rxy_76_77 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy77 as xy, xx77 as xx, rxy_77_78 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy78 as xy, xx78 as xx, rxy_78_79 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy79 as xy, xx79 as xx, rxy_79_80 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy80 as xy, xx80 as xx, rxy_80_81 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy81 as xy, xx81 as xx, rxy_81_82 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy82 as xy, xx82 as xx, rxy_82_83 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy83 as xy, xx83 as xx, rxy_83_84 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy84 as xy, xx84 as xx, rxy_84_85 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy85 as xy, xx85 as xx, rxy_85_86 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy86 as xy, xx86 as xx, rxy_86_87 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy87 as xy, xx87 as xx, rxy_87_88 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy88 as xy, xx88 as xx, rxy_88_89 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy89 as xy, xx89 as xx, rxy_89_90 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy90 as xy, xx90 as xx, rxy_90_91 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy91 as xy, xx91 as xx, rxy_91_92 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy92 as xy, xx92 as xx, rxy_92_93 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy93 as xy, xx93 as xx, rxy_93_94 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy94 as xy, xx94 as xx, rxy_94_95 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy95 as xy, xx95 as xx, rxy_95_96 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy96 as xy, xx96 as xx, rxy_96_97 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy97 as xy, xx97 as xx, rxy_97_98 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy98 as xy, xx98 as xx, rxy_98_99 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy99 as xy, xx99 as xx, rxy_99_100 as age FROM stage.censo_ccaa_2001_ranges UNION 
SELECT where_geon AS where_geoname, wkb_geometry AS where_boundary, xy100 as xy, xx100 as xx, rxy_100m as age FROM stage.censo_ccaa_2001_ranges);
