INSERT INTO ods.main (who_uploaded,
  what_project,
  what_data,
  where_geoname,
  where_boundary,
  when_reference,
  when_accessed,
  whose_provider,
  whose_url,
  what_variables,
  what_project_short,
  whose_provider_short,
  where_centroid) 

  SELECT who_uploaded,
  what_project,
  what_data,
  where_geoname,
  where_boundary,
  when_reference,
  when_accessed,
  whose_provider,
  whose_url,
  what_variable,
  what_project_short,
  whose_provider_short,
  where_centroid FROM stage.censo_ccaa_2001_final
