#
# Makefile for pg_chichinabo_dw
# 

EXTENSION = pg_chichinabo_dw
EXTVERSION = $(shell grep default_version $(EXTENSION).control | sed -e "s/default_version[[:space:]]*=[[:space:]]*'\([^']*\)'/\1/")


DOCS = $(wildcard doc/*.md)


all: $(EXTENSION)--$(EXTVERSION).sql

$(EXTENSION)--$(EXTVERSION).sql: sql/dw/schemas.sql \
sql/dw/types/*.sql \
\
sql/ods/tables/backers_list.sql \
sql/ods/tables/providers_list.sql \
sql/ods/tables/projects_list.sql \
sql/ods/tables/spatial_pool.sql \
sql/ods/tables/data_pool.sql \
\
sql/ods/functions/*.sql \
sql/ods/views/*.sql \
\
sql/dms/functions/*.sql

	cat $^ > $@

DATA = $(wildcard updates/*--*.sql) $(EXTENSION)--$(EXTVERSION).sql
EXTRA_CLEAN = $(EXTENSION)--$(EXTVERSION).sql
