#
# Makefile pg_popyramids
# 

EXTENSION = pg_popyramids
EXTVERSION = $(shell grep default_version $(EXTENSION).control | sed -e "s/default_version[[:space:]]*=[[:space:]]*'\([^']*\)'/\1/")

PG_CONFIG = pg_config

DOCS = $(wildcard doc/*.md)


all: $(EXTENSION)--$(EXTVERSION).sql

$(EXTENSION)--$(EXTVERSION).sql: sql/schemas.sql \
\
sql/ods/types/*.sql \
sql/ods/tables/backers_list.sql \
sql/ods/tables/providers_list.sql \
sql/ods/tables/projects_list.sql \
sql/ods/tables/pyramids_pool.sql \
sql/ods/views/*.sql \
sql/ods/triggers/*.sql \
\
sql/stage/functions/*.sql \
\
sql/dms/types/*.sql \
sql/dms/functions/*.sql

	cat $^ > $@

DATA = $(wildcard updates/*--*.sql) $(EXTENSION)--$(EXTVERSION).sql
EXTRA_CLEAN = $(EXTENSION)--$(EXTVERSION).sql
