#
# Makefile pg_popyramids
# 

EXTENSION = pg_popyramids
EXTVERSION = $(shell grep default_version $(EXTENSION).control | sed -e "s/default_version[[:space:]]*=[[:space:]]*'\([^']*\)'/\1/")

PG_CONFIG = pg_config

DOCS = $(wildcard doc/*.md)


all: $(EXTENSION)--$(EXTVERSION).sql

$(EXTENSION)--$(EXTVERSION).sql: sql/schemas.sql \
\
sql/ods/types/*.sql \
sql/ods/tables/*.sql \
\
sql/stage/functions/*.sql \
\
sql/dms/types/*.sql \
sql/dms/functions/*.sql \
\
sql/setup/triggers/*.sql \
sql/setup/indexes/*.sql

	cat $^ > $@

DATA = $(wildcard updates/*--*.sql) $(EXTENSION)--$(EXTVERSION).sql
EXTRA_CLEAN = $(EXTENSION)--$(EXTVERSION).sql
